### PR TITLE
make 'rk' importable and installable during pip install

### PR DESCRIPTION
**Pull request by basaks**
This PR makes `RegressionKriging` a package level importable class like the other (OK/UK)Kriging classes.

### CODE REVIEW

**Comment by rth** [comment]
Thanks for the  PR @basaks .

The issue is that `rk.py` imports sklearn and so importing it in the `__init__.py` would make scikit-learn a hard dependency which [it isn't now](https://github.com/bsmurphy/PyKrige/blob/bf0df599deccf257e859e02a64280538d4ed9398/setup.py#L28). I'm not sure we want to do that.

Maybe with the refactoring proposed in https://github.com/bsmurphy/PyKrige/issues/31#issuecomment-362962642 for pipelines using scikit-learn would make sense anyway. So let's at least wait before v1.4 is released before merging this. What do you think.

**Comment by rth** [comment]
> Anyway, it's affecting people who are trying to use RegressionKriging. We need to come up with a way forward.

True, but,
```py
from pykrige.rk import RegressionKriging
```
is not fundamentally different from
```py
from pykrige import RegressionKriging
```

Current [examples for other classes](http://pykrige.readthedocs.io/en/latest/overview.html#universal-kriging-example) also don't use the top level module FWIW.

Let's release v1.4 and try to come up with a solution for it.

**Comment by MuellerSeb** [comment]
you could add a try/except block in the ``__init__.py`` so it is only present if sklearn is importable.

**Comment by MuellerSeb** [comment]
I will resolve this in a separate PR.

**Pull request closed without merging**
